version: "3.7"
services:
  db:
    container_name: pgdb
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=mydb
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    command: postgres -c max_connections=200
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: test@example.com
      PGADMIN_DEFAULT_PASSWORD: example
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin

volumes:
  data:
  pgadmin-data:
